version: '3.0'
services:
  enterprise-canton-simple:
    image: digitalasset-canton-enterprise-docker.jfrog.io/digitalasset/canton-enterprise:${CANTON_VERSION:-2.3.6}
    restart: on-failure
    depends_on:
      - besu-1
      - besu-2
      - besu-3
      - besu-4
    tty: true
    expose:
      - "3001"
    environment:
      - ETHEREUM_DEMO_DIR
    volumes:
      - $ETHEREUM_DEMO_DIR/canton-conf/simple:/canton/simple
      - $DATA_DIR:/canton/testnet:ro
    command: >
      sh -c "cp -r /canton/testnet /canton/testnet-working;
      echo 'Starting Canton with a single sequencer to run a ping';
      bin/canton -c simple/config-example.conf \
          -c simple/tls.conf --bootstrap simple/ping.canton"
    ports:
      - "5011:5011"
      - "5021:5021"
      - "5012:5012"
      - "5022:5022"
    entrypoint: []