version: '3.0'
services:
  besu-1:
    image: hyperledger/besu:21.10
    expose:
      - 30303
    ports:
      - 8550:8550
    volumes:
      - $DATA_DIR:/home/testnet:ro
    user: root
    entrypoint: >
      bash -c "cd /home; cp -r testnet testnet-working; cd testnet-working; ./start-node.sh node1 8550 30303 in-container"

  besu-2:
    image: hyperledger/besu:21.10
    expose:
      - 30304
    ports:
      - 8551:8551
    volumes:
      - $DATA_DIR:/home/testnet:ro
    user: root
    entrypoint: >
      bash -c "cd /home; cp -r testnet testnet-working; cd testnet-working; ./start-node.sh node2 8551 30304 in-container"

  besu-3:
    image: hyperledger/besu:21.10
    expose:
      - 30305
    volumes:
      - $DATA_DIR:/home/testnet:ro
    user: root
    entrypoint: >
      bash -c "cd /home; cp -r testnet testnet-working; cd testnet-working; ./start-node.sh node3 8552 30305 in-container"

  besu-4:
    image: hyperledger/besu:21.10
    expose:
      - 30306
    volumes:
      - $DATA_DIR:/home/testnet:ro
    user: root
    entrypoint: >
      bash -c "cd /home; cp -r testnet testnet-working; cd testnet-working; ./start-node.sh node4 8553 30306 in-container"