version: '3.0'
services:
  enterprise-canton-advanced:
    image: digitalasset-canton-enterprise-docker.jfrog.io/digitalasset/canton-enterprise:${CANTON_VERSION:-2.3.6}
    restart: on-failure
    depends_on:
      - besu-1
      - besu-2
      - besu-3
      - besu-4
    tty: true
    expose:
      - "3001"
    environment:
      - ETHEREUM_DEMO_DIR
    volumes:
      - $ETHEREUM_DEMO_DIR/canton-conf/advanced:/canton/advanced:ro
      - $DATA_DIR:/canton/testnet:ro
    command: >
      sh -c "cp -r /canton/testnet /canton/testnet-working;
      echo 'Starting a Canton console to deploy the sequencer contract';
      bin/canton run advanced/sequencer_deployment.canton \
                 -c advanced/config-example.conf \
                 -c advanced/bip39-wallet.conf \
                 -c advanced/tls.conf | tee deploy.out;
      echo 'Using the output from the Canton console to configure the Ethereum sequencers';
      CONTRACT_CONF=$$(tail deploy.out -n 1);
      bin/canton -c advanced/config-example.conf \
          -c advanced/bip39-wallet.conf -c $$CONTRACT_CONF \
          -c advanced/utc-wallet.conf \
          -c advanced/tls.conf --bootstrap advanced/ping.canton"
    ports:
        - "5011:5011"
        - "5021:5021"
        - "5012:5012"
        - "5022:5022"
    entrypoint: []